### ISSUE TITLE
Auto-roll does not work anymore

### ISSUE THREAD

**Issue by JorgeFPastor** [chlegou/bitbot#2]
When touching the START button of the AUTO ROLL section, a message appears saying:

Network Not Available!
BitBot will try again shortly

Then a 5 minute countdown starts.

The message makes no much sense because the app is able to syncrhonize with the site and to display information about the account such like time for next free roll, balance, etc.

According to what I see in some referrals' activity, they've also stopped the auto-rolling. I guess some code could have changed in the freebitco.in site.

**Comment by chlegou** [comment]
Hi, the issue is fixed.
Please use official support area within the app, to reach me :) 

Thanks.
