### ISSUE TITLE
Open-sourcing app android project

### ISSUE THREAD

**Issue by DadiBit** [chlegou/bitbot#3]
While it looks like a great app, it could be dangerous to download apps that require a login to sites containing "real" money. For security reason I'd suggest open-sourcing the app so people can feel free to build that on their own and improve the work.

**Comment by vooraviboon** [comment]
Duplicate of #3

**Comment by vooraviboon** [comment]
[](30f3bced-d905-46b2-ae83-315a2679f27c)

**Comment by rilmah27** [comment]
Goood

**Comment by rilmah27** [comment]
Tidak ada masalah

**Comment by rilmah27** [comment]
> Gandakan [# 3](https://github.com/chlegou/bitbot/issues/3)

Gak ada masalah

**Comment by rilmah27** [comment]
Baik baik saja selama ini

**Comment by rilmah27** [comment]
Saya pengguna merasa nyaman
