### ISSUE TITLE
Unfortunately, bitbot has close.

### ISSUE THREAD

**Issue by Lynx-Hacker** [chlegou/bitbot#6]
### **Cannot touch any button**

_Dear developer
  I have an serious issue. I just want to know why I can't tap any button. When I tap the button, it show `unfotunately, bitbot has close'. Please help me..I've contact all your account but there is no reply.._

**Comment by Les23** [comment]
I'm only a user. I don't own or develop the app

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by rilmah27** [comment]
Saya tidak menemukan masalah
